force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <label>Shelter</label>
    <referenceTo>Shelter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Adopted_Animal_Count__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Animal_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Adopted Animal Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnimalTriggerTest.cls
@IsTest
public class AnimalTriggerTest {
    private static Shelter__c createShelter() {
        Shelter__c shelter = new Shelter__c(
            Name = 'Test Shelter'
        );
        insert shelter;

        return shelter;
    } 

    private static List<Animal__c> createAnimals(Shelter__c shelter, Integer countAdopted, Integer countAll) {
        List<Animal__c> animals = new List<Animal__c>();

        for (Integer i = 0; i < countAll; i++) {
            Animal__c animal = new Animal__c(
                    Name = 'Test animal ' + i,
                    Shelter__c = shelter.Id
                );
            if (i < countAdopted) {
                animal.Status__c = AnimalTriggerHandler.ANIMAL_STATUS_ADOPTED;
            }

            animals.add(animal);
        }
        insert animals;

        return animals;
    }

    @IsTest
    static void testAdoptedAnimalsCount() {
        Shelter__c shelter = createShelter();
        Integer adoptedCount = 4;
        Integer allCount = 9;
        
        List<Animal__c> animals = createAnimals(shelter, adoptedCount, allCount);

        shelter = [SELECT Id, Adopted_Animal_Count__c FROM Shelter__c WHERE Id = :shelter.Id];

        System.assertEquals(adoptedCount, shelter.Adopted_Animal_Count__c, 'Food points after insert are incorrect');
    }
}